### ISSUE TITLE
could you share srm_resnet50.pth,thanks

### ISSUE THREAD

**Issue by ZZH2950228** [EvgenyKashin/SRMnet#5]

**Comment by EvgenyKashin** [comment]
Hi, I published only `srm_resnet32` weights https://github.com/EvgenyKashin/SRMnet/blob/master/weights/cifar_best_srmnet.pth But it should be easy to add  `srm_resnet50` following this code https://github.com/EvgenyKashin/SRMnet/blob/master/models/resnet_with_block.py
